### Site metadata ###

site_name: pyobjson - Python Object JSON Tool
site_description: Utility library for serializing/deserializing custom Python objects to/from JSON.
site_url: https://pyobjson.wrencode.dev
site_author: "Wren J. Rudolph for Wrencode, LLC"

repo_url: https://github.com/wrencode/pyobjson
edit_uri: ""

### Build settings ###

extra:
  version: !ENV [PYTHON_PACKAGE_VERSION, 'vX.X.X']

docs_dir: docs-mkdocs
site_dir: docs

theme:
#  name: mkdocs
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true
  navigation_depth: 6
  include_sidebar: true
  logo: wrencode-logo.svg

extra_css:
  - extra.css

extra_javascript:
  - extra.js

nav:
  - Introduction: index.md
  - README: readme.md
  - Deployment: deployment.md
  - Package:
    - pyobjson: base.md
    - Data Tools: data.md
    - Utilities: utils.md
  - Tests:
    - PyTest: tests.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
  - sane_lists
  - smarty
  - codehilite
  - fenced_code

plugins:
  - search
  - autorefs
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
#      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            separate_signature: true
            show_submodules: true
            docstring_section_style: table
            members_order: source
            summary: true
